const express = require('express')
const router = express.Router()
const userController = require('../../controllers/userController')
const multer = require('multer')
const upload = multer({ dest: 'temp/' })

router.get('/top', userController.getTopUser)
router.post('/favorite/:mountainId', userController.addFavorite)
router.delete('/favorite/:mountainId', userController.removeFavorite)
router.post('/following/:userId', userController.addFollowing)
router.delete('/following/:userId', userController.removeFollowing)
router.get('/:id/edit', userController.editUser)
router.put('/:id', upload.single('image'), userController.putUser)
router.get('/:id', userController.getUser)
module.exports = router
